[project]
name = "python-cheat-sheet"
version = "0.0.1"
authors = [{name = "Konrad Okarmus"}]
requires-python = ">= 3.12"

[project.scripts]
py-cheat-sheet = "python_cheat_sheet.main:main"

[tool.poetry]
requires-poetry = ">=2.0"
packages = [
    { include = "python_cheat_sheet", from = "src" }
]
